---
title: "BlogsMedical_F"
author: "Linda Lee"
date: "2019/7/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Import library
```{r}
library(dplyr)
library(xml2)
library(rvest)
library(wordcloud)
library(stringr)
```

### Read the top web page 
```{r}
page_prefix <- "https://www.pixnet.net/blog/articles/category/33"
```

### Functions

#### findLastPage()
```{r}
findLastPage <- function(urlpath){
  full_page <- read_html(urlpath)
  nav_nodes <- html_node(full_page,".page") %>% html_nodes("a")
  attr <- nav_nodes %>% html_attr("href")
  
  checkball <- c("pageID","href")
  pool <- c(.Machine$integer.max)
  for(node in nav_nodes){
    v <- html_text(node)
    href <- node %>% html_attr("href") %>% toString()
    checkball<-data.frame("pageID"=v,"href"=href) %>% rbind(checkball)
    if(str_detect(href,"vascript")==TRUE){
      pool <- c(pool,v)
    }
  }
  ret <- c(checkball,pool,min(unlist(pool)))
  
  return(ret)
}
```

#### df_page()
```{r}
df_page <- function(urlpath){
  full_page <- read_html(urlpath)
  all_nodes<- html_node(full_page,xpath="/html/body")
  rank1_title <- all_nodes %>% html_node("h3>a")

  titles <- html_attr(rank1_title,"title")

  urls <- html_attr(rank1_title,"href")

  df <- data.frame("title"=titles,"URL"=urls)

  rank <- 10   # get the top-10
  for(i in 2:rank){
    rank_tag <- paste0(".rank-",i)
    cat(rank_tag)
    block <- html_node(all_nodes, rank_tag) %>% html_node("h3>a")
    title <- html_text(block)
    theUrl <- html_attr(block,"href")
    df <- data.frame("title"=title,"URL"=theUrl) %>% rbind(df)
  }

  return(df)
}
```

### Verify
```{r}
lastPageID <- findLastPage(page_prefix)
lastPageID
```

```{r}
data <- df_page(page_prefix)
data
```